# Basic Pytorch methods

### We will be going through 5 basic Pytorch methods to operate on Pytorch tensors

An short introduction about PyTorch and about the chosen functions. 
- torch.rand
- torch.chunk
- torch.cat
- torch.sort
- torch.clamp

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.rand

Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)<br>The size of the tensor can be passed as a list or tuple.


In [0]:
# Example 1 - working (change this)
torch.rand(2,3)

tensor([[0.8648, 0.5915, 0.0946],
        [0.3780, 0.8509, 0.3354]])

The above code returned a tensor of size (2,3) having values betwen 0 and 1.

In [0]:
# Example 2 - working
torch.rand(4)

tensor([0.3472, 0.1495, 0.8549, 0.4025])

The above code returned a 4 x 1 tensor. It is a 1D tensor.

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
torch.rand(1.1)

TypeError: ignored

We can not pass float values as size of a tensor.

We can use this method to create tensors with random values which lie between 0 and 1. They can be used as weight tensors in model building.

## Function 2 - torch.chunk

Splits a tensor into a specific number of chunks.<br>
Parameters:
- tensor
-number of parts
- dimension across which to divide

In [7]:
# Example 1 - working
x=torch.tensor([1,2,3,4,5,6,7,8,9])
x1,x2,x3=torch.chunk(x,3,0)
x1,x2,x3

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

The fucntion divided the tensor **x** into 3 equal parts.


In [8]:
# Example 2 - working
y=torch.tensor([[1,2,3],[4,5,6]])
y1,y2=torch.chunk(y,2,1)
y1,y2

(tensor([[1, 2],
         [4, 5]]), tensor([[3],
         [6]]))

Here as we provided the dimension as **1**, it divided the tensor column-wise.

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
torch.chunk(x,3,1)

IndexError: ignored

As **x** is a 1D tensor, it shown an error when we asked the function to divide the tensor by 2nd dimension.

We can use the method to divide the tensor into parts or batches to operate on them separately or iteratively rather than all the values at same time.

## Function 3 - torch.cat

Concatenates the given sequence of seq tensors in the given dimension.<br> All tensors must either have the same shape (except in the concatenating dimension) or be empty.<br>
Parameters:
- list or tuple of tensors
- dimension along which to concat
- output tensor


In [10]:
# Example 1 - working
torch.cat((x1,x2,x3),0)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

We combined here three tensors (we got by splitting tensor **x**) across dimension **0**(row) to get **x** again.

In [13]:
# Example 2 - working
torch.cat((y1,y2),1)

tensor([[1, 2, 3],
        [4, 5, 6]])

We combined here three tensors (we got by splitting tensor **y**) across dimension **1**(column) to get **y** again.

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
torch.cat((x1,y1),0)

RuntimeError: ignored

For concatenation, the tensors should have same dimension.

We can use this method to join tensors. But we need to ensure that the tensors should be same across all dimensions except across which we concat.

## Function 4 - torch.sort

Sorts the elements of the input tensor along a given dimension in ascending order by value.

If dim is not given, the last dimension of the input is chosen.

If descending is True then the elements are sorted in descending order by value.

Parameters:
- tensor
- dimension across which to sort (optional)
- descending (optional)
- output tensor (optional)

Returns sorted tensor and indices.

In [19]:
# Example 1 - working
t=torch.tensor([[10,8,30],[40,5,6]])
tensor,indices=torch.sort(t)
print(tensor)
print(indices)

tensor([[ 8, 10, 30],
        [ 5,  6, 40]])
tensor([[1, 0, 2],
        [1, 2, 0]])


The function returned the sorted tensor across its last dimension i.e. it compared elements of the columns of each row and arranged them.

It also returned the positions of the indices of values after sorting.

In [20]:
# Example 2 - working
tensor, indices=torch.sort(t,0)
print(tensor)
print(indices)

tensor([[10,  5,  6],
        [40,  8, 30]])
tensor([[0, 1, 1],
        [1, 0, 0]])


We can see the tensor sorted across dimension 0 i.e. the values in same column number of the rows and sorted.

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
tensor, indices= torch.sort(t,dim=2)


IndexError: ignored

The error is there as we set dimension as 2. But the dimensions can be 0 or 1 as it is a 2D tensor.

So, we can use this method to sort the tensors in required dimensions (both in ascending and descending order)

## Function 5 - torch.clamp

Clamp all elements in input into the range [ min, max ] and return a resulting tensor.

If in a tensor:
- value > **max** then value is converted into max value
- value < **min** then value is converted into min value
- else **min** < value < **max** then no change

Parameters:
- tensor
- min
- max
- output tensor

In [35]:
# Example 1 - working
c=torch.tensor([1,2,3,4,5.5,6,6.2])
torch.clamp(c,2,6)

tensor([2.0000, 2.0000, 3.0000, 4.0000, 5.5000, 6.0000, 6.0000])

Here the first value **1** has been converted into **min value** i.e. **2** and **6.2** has been converted into **max value** i.e. **6**.

In [36]:
# Example 2 - working
torch.clamp(c,max=6)

tensor([1.0000, 2.0000, 3.0000, 4.0000, 5.5000, 6.0000, 6.0000])

We can also mention only the **min** or **max** value.

Here as we have mentioned only **max** as **6**, only the values (i.e. 6.2) is converted to 6.

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
c=torch.tensor([1,0,1,0],dtype=torch.bool)
torch.clamp(c,2,6)

RuntimeError: ignored

We can not apply this **clamp** method on tensors with data types other than which are of numeric types.

This method comes really handy when we need to add a limit to our tensor values.

## Conclusion

In this notebook we came across 5 basic methods of pytorch functions to work with tensors. Along with when the functions can be used, we should keep an eye on the conditions under which they break.

## Reference Links
You can go through the official Pytorch documentation which has a plethora of such methods with good examples
* Official documentation for Pytorch : https://pytorch.org/docs/stable/tensors.html


In [42]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 5.6MB/s 


In [0]:
import jovian

In [45]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
